"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _City:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_City.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BUCHAREST: _City.ValueType  # 0
    CLUJ: _City.ValueType  # 1
    TIMISOARA: _City.ValueType  # 2
    IASI: _City.ValueType  # 3
    CONSTANTA: _City.ValueType  # 4

class City(_City, metaclass=_CityEnumTypeWrapper): ...

BUCHAREST: City.ValueType  # 0
CLUJ: City.ValueType  # 1
TIMISOARA: City.ValueType  # 2
IASI: City.ValueType  # 3
CONSTANTA: City.ValueType  # 4
global___City = City

class _Direction:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DirectionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Direction.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NE: _Direction.ValueType  # 0
    NW: _Direction.ValueType  # 1
    SE: _Direction.ValueType  # 2
    SW: _Direction.ValueType  # 3

class Direction(_Direction, metaclass=_DirectionEnumTypeWrapper): ...

NE: Direction.ValueType  # 0
NW: Direction.ValueType  # 1
SE: Direction.ValueType  # 2
SW: Direction.ValueType  # 3
global___Direction = Direction

class _Comparator:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ComparatorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Comparator.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EQUAL: _Comparator.ValueType  # 0
    GREATER: _Comparator.ValueType  # 1
    GREATER_EQUAL: _Comparator.ValueType  # 2
    LESS: _Comparator.ValueType  # 3
    LESS_EQUAL: _Comparator.ValueType  # 4

class Comparator(_Comparator, metaclass=_ComparatorEnumTypeWrapper): ...

EQUAL: Comparator.ValueType  # 0
GREATER: Comparator.ValueType  # 1
GREATER_EQUAL: Comparator.ValueType  # 2
LESS: Comparator.ValueType  # 3
LESS_EQUAL: Comparator.ValueType  # 4
global___Comparator = Comparator

class _AggregateType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AggregateTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AggregateType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SUM: _AggregateType.ValueType  # 0
    AVG: _AggregateType.ValueType  # 1
    MIN: _AggregateType.ValueType  # 2
    MAX: _AggregateType.ValueType  # 3

class AggregateType(_AggregateType, metaclass=_AggregateTypeEnumTypeWrapper): ...

SUM: AggregateType.ValueType  # 0
AVG: AggregateType.ValueType  # 1
MIN: AggregateType.ValueType  # 2
MAX: AggregateType.ValueType  # 3
global___AggregateType = AggregateType

class _SubscriptionType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SubscriptionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SubscriptionType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SUBSCRIBE: _SubscriptionType.ValueType  # 0
    UNSUBSCRIBE: _SubscriptionType.ValueType  # 1

class SubscriptionType(_SubscriptionType, metaclass=_SubscriptionTypeEnumTypeWrapper): ...

SUBSCRIBE: SubscriptionType.ValueType  # 0
UNSUBSCRIBE: SubscriptionType.ValueType  # 1
global___SubscriptionType = SubscriptionType

class _MatchType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MatchTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MatchType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AGGREGATION: _MatchType.ValueType  # 0
    DIRECT: _MatchType.ValueType  # 1

class MatchType(_MatchType, metaclass=_MatchTypeEnumTypeWrapper): ...

AGGREGATION: MatchType.ValueType  # 0
DIRECT: MatchType.ValueType  # 1
global___MatchType = MatchType

@typing.final
class Publication(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATIONID_FIELD_NUMBER: builtins.int
    CITY_FIELD_NUMBER: builtins.int
    TEMP_FIELD_NUMBER: builtins.int
    RAIN_FIELD_NUMBER: builtins.int
    WIND_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    DATE_FIELD_NUMBER: builtins.int
    PARSED_FIELDS_FIELD_NUMBER: builtins.int
    ALL_SUBSCRIPTIONS_FIELD_NUMBER: builtins.int
    REMAINING_SUBSCRIPTIONS_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    stationid: builtins.int
    city: global___City.ValueType
    temp: builtins.int
    rain: builtins.float
    wind: builtins.int
    direction: global___Direction.ValueType
    date: builtins.str
    all_subscriptions: builtins.bool
    timestamp: builtins.int
    """Unix timestamp in milliseconds"""
    @property
    def parsed_fields(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def remaining_subscriptions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        stationid: builtins.int = ...,
        city: global___City.ValueType = ...,
        temp: builtins.int = ...,
        rain: builtins.float = ...,
        wind: builtins.int = ...,
        direction: global___Direction.ValueType = ...,
        date: builtins.str = ...,
        parsed_fields: collections.abc.Iterable[builtins.str] | None = ...,
        all_subscriptions: builtins.bool = ...,
        remaining_subscriptions: collections.abc.Iterable[builtins.str] | None = ...,
        timestamp: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["all_subscriptions", b"all_subscriptions", "city", b"city", "date", b"date", "direction", b"direction", "parsed_fields", b"parsed_fields", "rain", b"rain", "remaining_subscriptions", b"remaining_subscriptions", "stationid", b"stationid", "temp", b"temp", "timestamp", b"timestamp", "wind", b"wind"]) -> None: ...

global___Publication = Publication

@typing.final
class Subscription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    STATIONID_FIELD_NUMBER: builtins.int
    STATIONID_COMPARATOR_FIELD_NUMBER: builtins.int
    CITY_FIELD_NUMBER: builtins.int
    CITY_COMPARATOR_FIELD_NUMBER: builtins.int
    TEMP_FIELD_NUMBER: builtins.int
    TEMP_COMPARATOR_FIELD_NUMBER: builtins.int
    RAIN_FIELD_NUMBER: builtins.int
    RAIN_COMPARATOR_FIELD_NUMBER: builtins.int
    WIND_FIELD_NUMBER: builtins.int
    WIND_COMPARATOR_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    DIRECTION_COMPARATOR_FIELD_NUMBER: builtins.int
    DATE_FIELD_NUMBER: builtins.int
    DATE_COMPARATOR_FIELD_NUMBER: builtins.int
    TEMP_AGG_FIELD_NUMBER: builtins.int
    TEMP_AGG_TYPE_FIELD_NUMBER: builtins.int
    TEMP_AGG_COMPARATOR_FIELD_NUMBER: builtins.int
    RAIN_AGG_FIELD_NUMBER: builtins.int
    RAIN_AGG_TYPE_FIELD_NUMBER: builtins.int
    RAIN_AGG_COMPARATOR_FIELD_NUMBER: builtins.int
    WIND_AGG_FIELD_NUMBER: builtins.int
    WIND_AGG_TYPE_FIELD_NUMBER: builtins.int
    WIND_AGG_COMPARATOR_FIELD_NUMBER: builtins.int
    PARSED_FIELDS_FIELD_NUMBER: builtins.int
    ALL_SUBSCRIPTIONS_FIELD_NUMBER: builtins.int
    RETURN_TOPIC_FIELD_NUMBER: builtins.int
    id: builtins.str
    stationid: builtins.int
    stationid_comparator: global___Comparator.ValueType
    city: global___City.ValueType
    city_comparator: global___Comparator.ValueType
    temp: builtins.int
    temp_comparator: global___Comparator.ValueType
    rain: builtins.float
    rain_comparator: global___Comparator.ValueType
    wind: builtins.int
    wind_comparator: global___Comparator.ValueType
    direction: global___Direction.ValueType
    direction_comparator: global___Comparator.ValueType
    date: builtins.str
    date_comparator: global___Comparator.ValueType
    temp_agg: builtins.int
    temp_agg_type: global___AggregateType.ValueType
    temp_agg_comparator: global___Comparator.ValueType
    rain_agg: builtins.float
    rain_agg_type: global___AggregateType.ValueType
    rain_agg_comparator: global___Comparator.ValueType
    wind_agg: builtins.int
    wind_agg_type: global___AggregateType.ValueType
    wind_agg_comparator: global___Comparator.ValueType
    all_subscriptions: builtins.bool
    return_topic: builtins.str
    @property
    def parsed_fields(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        stationid: builtins.int | None = ...,
        stationid_comparator: global___Comparator.ValueType | None = ...,
        city: global___City.ValueType | None = ...,
        city_comparator: global___Comparator.ValueType | None = ...,
        temp: builtins.int | None = ...,
        temp_comparator: global___Comparator.ValueType | None = ...,
        rain: builtins.float | None = ...,
        rain_comparator: global___Comparator.ValueType | None = ...,
        wind: builtins.int | None = ...,
        wind_comparator: global___Comparator.ValueType | None = ...,
        direction: global___Direction.ValueType | None = ...,
        direction_comparator: global___Comparator.ValueType | None = ...,
        date: builtins.str | None = ...,
        date_comparator: global___Comparator.ValueType | None = ...,
        temp_agg: builtins.int | None = ...,
        temp_agg_type: global___AggregateType.ValueType | None = ...,
        temp_agg_comparator: global___Comparator.ValueType | None = ...,
        rain_agg: builtins.float | None = ...,
        rain_agg_type: global___AggregateType.ValueType | None = ...,
        rain_agg_comparator: global___Comparator.ValueType | None = ...,
        wind_agg: builtins.int | None = ...,
        wind_agg_type: global___AggregateType.ValueType | None = ...,
        wind_agg_comparator: global___Comparator.ValueType | None = ...,
        parsed_fields: collections.abc.Iterable[builtins.str] | None = ...,
        all_subscriptions: builtins.bool = ...,
        return_topic: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_city", b"_city", "_city_comparator", b"_city_comparator", "_date", b"_date", "_date_comparator", b"_date_comparator", "_direction", b"_direction", "_direction_comparator", b"_direction_comparator", "_rain", b"_rain", "_rain_agg", b"_rain_agg", "_rain_agg_comparator", b"_rain_agg_comparator", "_rain_agg_type", b"_rain_agg_type", "_rain_comparator", b"_rain_comparator", "_stationid", b"_stationid", "_stationid_comparator", b"_stationid_comparator", "_temp", b"_temp", "_temp_agg", b"_temp_agg", "_temp_agg_comparator", b"_temp_agg_comparator", "_temp_agg_type", b"_temp_agg_type", "_temp_comparator", b"_temp_comparator", "_wind", b"_wind", "_wind_agg", b"_wind_agg", "_wind_agg_comparator", b"_wind_agg_comparator", "_wind_agg_type", b"_wind_agg_type", "_wind_comparator", b"_wind_comparator", "city", b"city", "city_comparator", b"city_comparator", "date", b"date", "date_comparator", b"date_comparator", "direction", b"direction", "direction_comparator", b"direction_comparator", "rain", b"rain", "rain_agg", b"rain_agg", "rain_agg_comparator", b"rain_agg_comparator", "rain_agg_type", b"rain_agg_type", "rain_comparator", b"rain_comparator", "stationid", b"stationid", "stationid_comparator", b"stationid_comparator", "temp", b"temp", "temp_agg", b"temp_agg", "temp_agg_comparator", b"temp_agg_comparator", "temp_agg_type", b"temp_agg_type", "temp_comparator", b"temp_comparator", "wind", b"wind", "wind_agg", b"wind_agg", "wind_agg_comparator", b"wind_agg_comparator", "wind_agg_type", b"wind_agg_type", "wind_comparator", b"wind_comparator"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_city", b"_city", "_city_comparator", b"_city_comparator", "_date", b"_date", "_date_comparator", b"_date_comparator", "_direction", b"_direction", "_direction_comparator", b"_direction_comparator", "_rain", b"_rain", "_rain_agg", b"_rain_agg", "_rain_agg_comparator", b"_rain_agg_comparator", "_rain_agg_type", b"_rain_agg_type", "_rain_comparator", b"_rain_comparator", "_stationid", b"_stationid", "_stationid_comparator", b"_stationid_comparator", "_temp", b"_temp", "_temp_agg", b"_temp_agg", "_temp_agg_comparator", b"_temp_agg_comparator", "_temp_agg_type", b"_temp_agg_type", "_temp_comparator", b"_temp_comparator", "_wind", b"_wind", "_wind_agg", b"_wind_agg", "_wind_agg_comparator", b"_wind_agg_comparator", "_wind_agg_type", b"_wind_agg_type", "_wind_comparator", b"_wind_comparator", "all_subscriptions", b"all_subscriptions", "city", b"city", "city_comparator", b"city_comparator", "date", b"date", "date_comparator", b"date_comparator", "direction", b"direction", "direction_comparator", b"direction_comparator", "id", b"id", "parsed_fields", b"parsed_fields", "rain", b"rain", "rain_agg", b"rain_agg", "rain_agg_comparator", b"rain_agg_comparator", "rain_agg_type", b"rain_agg_type", "rain_comparator", b"rain_comparator", "return_topic", b"return_topic", "stationid", b"stationid", "stationid_comparator", b"stationid_comparator", "temp", b"temp", "temp_agg", b"temp_agg", "temp_agg_comparator", b"temp_agg_comparator", "temp_agg_type", b"temp_agg_type", "temp_comparator", b"temp_comparator", "wind", b"wind", "wind_agg", b"wind_agg", "wind_agg_comparator", b"wind_agg_comparator", "wind_agg_type", b"wind_agg_type", "wind_comparator", b"wind_comparator"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_city", b"_city"]) -> typing.Literal["city"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_city_comparator", b"_city_comparator"]) -> typing.Literal["city_comparator"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_date", b"_date"]) -> typing.Literal["date"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_date_comparator", b"_date_comparator"]) -> typing.Literal["date_comparator"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_direction", b"_direction"]) -> typing.Literal["direction"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_direction_comparator", b"_direction_comparator"]) -> typing.Literal["direction_comparator"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_rain", b"_rain"]) -> typing.Literal["rain"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_rain_agg", b"_rain_agg"]) -> typing.Literal["rain_agg"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_rain_agg_comparator", b"_rain_agg_comparator"]) -> typing.Literal["rain_agg_comparator"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_rain_agg_type", b"_rain_agg_type"]) -> typing.Literal["rain_agg_type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_rain_comparator", b"_rain_comparator"]) -> typing.Literal["rain_comparator"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_stationid", b"_stationid"]) -> typing.Literal["stationid"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_stationid_comparator", b"_stationid_comparator"]) -> typing.Literal["stationid_comparator"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_temp", b"_temp"]) -> typing.Literal["temp"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_temp_agg", b"_temp_agg"]) -> typing.Literal["temp_agg"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_temp_agg_comparator", b"_temp_agg_comparator"]) -> typing.Literal["temp_agg_comparator"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_temp_agg_type", b"_temp_agg_type"]) -> typing.Literal["temp_agg_type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_temp_comparator", b"_temp_comparator"]) -> typing.Literal["temp_comparator"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_wind", b"_wind"]) -> typing.Literal["wind"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_wind_agg", b"_wind_agg"]) -> typing.Literal["wind_agg"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_wind_agg_comparator", b"_wind_agg_comparator"]) -> typing.Literal["wind_agg_comparator"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_wind_agg_type", b"_wind_agg_type"]) -> typing.Literal["wind_agg_type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_wind_comparator", b"_wind_comparator"]) -> typing.Literal["wind_comparator"] | None: ...

global___Subscription = Subscription

@typing.final
class SubscriptionMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIPTION_TYPE_FIELD_NUMBER: builtins.int
    SUBSCRIPTIONS_FIELD_NUMBER: builtins.int
    subscription_type: global___SubscriptionType.ValueType
    @property
    def subscriptions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Subscription]: ...
    def __init__(
        self,
        *,
        subscription_type: global___SubscriptionType.ValueType = ...,
        subscriptions: collections.abc.Iterable[global___Subscription] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["subscription_type", b"subscription_type", "subscriptions", b"subscriptions"]) -> None: ...

global___SubscriptionMessage = SubscriptionMessage

@typing.final
class MatchedPublicationWithSubscription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLICATION_FIELD_NUMBER: builtins.int
    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    MATCH_TYPE_FIELD_NUMBER: builtins.int
    match_type: global___MatchType.ValueType
    @property
    def publication(self) -> global___Publication: ...
    @property
    def subscription(self) -> global___Subscription: ...
    def __init__(
        self,
        *,
        publication: global___Publication | None = ...,
        subscription: global___Subscription | None = ...,
        match_type: global___MatchType.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["publication", b"publication", "subscription", b"subscription"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["match_type", b"match_type", "publication", b"publication", "subscription", b"subscription"]) -> None: ...

global___MatchedPublicationWithSubscription = MatchedPublicationWithSubscription
