# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pubsub.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pubsub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpubsub.proto\"\x85\x01\n\x0bPublication\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tstationid\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x0c\n\x04temp\x18\x04 \x01(\x05\x12\x0c\n\x04rain\x18\x05 \x01(\x02\x12\x0c\n\x04wind\x18\x06 \x01(\x05\x12\x11\n\tdirection\x18\x07 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x08 \x01(\t\"?\n\rComparableInt\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x1f\n\ncomparator\x18\x02 \x01(\x0e\x32\x0b.Comparator\"A\n\x0f\x43omparableFloat\x12\r\n\x05value\x18\x01 \x01(\x02\x12\x1f\n\ncomparator\x18\x02 \x01(\x0e\x32\x0b.Comparator\"B\n\x10\x43omparableString\x12\r\n\x05value\x18\x01 \x01(\t\x12\x1f\n\ncomparator\x18\x02 \x01(\x0e\x32\x0b.Comparator\"\x84\x02\n\x0cSubscription\x12\n\n\x02id\x18\x01 \x01(\t\x12$\n\tstationid\x18\x02 \x01(\x0b\x32\x11.ComparableString\x12\x1f\n\x04\x63ity\x18\x03 \x01(\x0b\x32\x11.ComparableString\x12\x1c\n\x04temp\x18\x04 \x01(\x0b\x32\x0e.ComparableInt\x12\x1e\n\x04rain\x18\x05 \x01(\x0b\x32\x10.ComparableFloat\x12\x1c\n\x04wind\x18\x06 \x01(\x0b\x32\x0e.ComparableInt\x12$\n\tdirection\x18\x07 \x01(\x0b\x32\x11.ComparableString\x12\x1f\n\x04\x64\x61te\x18\x08 \x01(\x0b\x32\x11.ComparableString*Q\n\nComparator\x12\t\n\x05\x45QUAL\x10\x00\x12\x0b\n\x07GREATER\x10\x01\x12\x11\n\rGREATER_EQUAL\x10\x02\x12\x08\n\x04LESS\x10\x03\x12\x0e\n\nLESS_EQUAL\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pubsub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPARATOR']._serialized_start=615
  _globals['_COMPARATOR']._serialized_end=696
  _globals['_PUBLICATION']._serialized_start=17
  _globals['_PUBLICATION']._serialized_end=150
  _globals['_COMPARABLEINT']._serialized_start=152
  _globals['_COMPARABLEINT']._serialized_end=215
  _globals['_COMPARABLEFLOAT']._serialized_start=217
  _globals['_COMPARABLEFLOAT']._serialized_end=282
  _globals['_COMPARABLESTRING']._serialized_start=284
  _globals['_COMPARABLESTRING']._serialized_end=350
  _globals['_SUBSCRIPTION']._serialized_start=353
  _globals['_SUBSCRIPTION']._serialized_end=613
# @@protoc_insertion_point(module_scope)
